# Generated by Django 6.1 on 2026-09-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur_nom', models.CharField(default='Administration', help_text='Nom affiché comme auteur de la publication.', max_length=150)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('publiee', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
