# Generated by Django 6.1 on 2026-09-06 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_formation', models.CharField(choices=[('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('PDF', 'PDF')], max_length=10)),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='formations/miniatures/')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='formations/fichiers/')),
                ('lien_externe', models.URLField(blank=True, help_text="Lien externe si le contenu n'est pas hébergé ici")),
                ('active', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.categorie')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
